apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nfo.fullname" . }}
  labels:
    {{- include "nfo.labels" . | nindent 4 }}
data:
  debug: {{ .Values.config.debug | quote }}
  allowed-hosts: {{ .Values.config.allowedHosts | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nfo.fullname" . }}-config
  labels:
    {{- include "nfo.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "config/config.yaml" | indent 4 }}
