apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nfo.fullname" . }}
  labels:
    {{- include "nfo.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.config.secretKey | b64enc | quote }}
